Feat/update dependecy cqrs&buckets
atls/services pull request #23
Opened 2023-09-30 11:18 UTC by shifuwww

2023-10-02 07:20 UTC, SlumberyDude requested changes

2023-10-02 07:20 UTC, SlumberyDude commented on package.json
> +    "@nestjs/cqrs": "8.0.2",
Тут можно сделать не совсем глобальный лок версии, а указать конкретный воркспейс. Можно сделать 8 версию у `@files/buckets-config-adapter-module` либо 10 версию у `@files/infrastructure-module` и `@files/service-entrypoint`

2023-10-02 07:42 UTC, SlumberyDude commented
@TorinAsakura Привет, тут превью чек не проходит, падает на шаге `Login to Google Container Registry`
```
Run echo -e $GCR_KEYFILE | docker login -u _json_key --password-stdin https://eu.gcr.io/
Error: Cannot perform an interactive login from a non TTY device
Error: Process completed with exit code 1.
```
Такое ощущение, что `$GCR_KEYFILE` невалиден

2023-10-02 12:55 UTC, shifuwww commented on package.json
> +    "@nestjs/cqrs": "8.0.2",
>Тут можно сделать не совсем глобальный лок версии, а указать конкретный воркспейс. Можно сделать 8 версию у @files/buckets-config-adapter-module либо 10 версию у @files/infrastructure-module и @files/service-entrypoint
>
Получается не делать заплатку в resolution в корне файла. А локально устновить 8 версию или имеется ввиду проставить resolution в `@files/buckets-config-adapter-module

2023-10-02 12:58 UTC, SlumberyDude commented on package.json
> +    "@nestjs/cqrs": "8.0.2",
@shifuwww Вот посмотри тут https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/. Можно указать то, для какого пакета будет устанавливаться зависимость.

2023-10-02 13:31 UTC, TorinAsakura commented
> @TorinAsakura Привет, тут превью чек не проходит, падает на шаге `Login to Google Container Registry`
> 
> ```
> Run echo -e $GCR_KEYFILE | docker login -u _json_key --password-stdin https://eu.gcr.io/
> Error: Cannot perform an interactive login from a non TTY device
> Error: Process completed with exit code 1.
> ```
> 
> Такое ощущение, что `$GCR_KEYFILE` невалиден

агаг, если быть точным - его просто нет, оставьте этот ПР пока да на меня перевесьте

2023-10-02 16:06 UTC, shifuwww commented on package.json
> +    "@nestjs/cqrs": "8.0.2",
> @shifuwww Вот посмотри тут https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/. Можно указать то, для какого пакета будет устанавливаться зависимость.
>
Вроде бы локально сделал заплатку но ошибки снова появились `"@files/buckets-config-adapter-module/@nestjs/cqrs": "8.0.2"`

2023-10-02 20:38 UTC, TorinAsakura commented
@shifuwww почему у ПРа нет задачи?

2023-10-02 20:43 UTC, shifuwww commented
> @shifuwww почему у ПРа нет задачи?
>
@TorinAsakura Добавил

2024-01-10 07:12 UTC, Nelfimov requested changes
доработать

2024-01-11 22:12 UTC, TorinAsakura commented
> доработать

ты это кому?

2024-01-12 05:36 UTC, Nelfimov commented
Себе конечно. Иначе висит в списке на ревью

2024-04-08 11:37 UTC, Nelfimov requested changes
на доработку

2024-09-12 20:01 UTC, TorinAsakura commented
@Nelfimov

2025-02-24 16:39 UTC, Amiditin commented
Выполнено здесь https://github.com/atls/services/pull/28

2025-02-24 16:39 UTC, closed without merging